# download L2 data

From SWOT Helpdesk documentation, Data access - External providers - Access SWOT LR data on AVISO FTP

local cache path: `/work/HELPDESK_SWOTLR/commun/data/swot/cache/`

In [1]:
import os
from tqdm import tqdm

import numpy as np
from pprint import pprint

import logging
logging.basicConfig(level=logging.INFO)

from ocean_tools.interfaces.swath.io import NetcdfFilesFTPSwotLRL2

In [2]:
#product_type = "basic"
product_type = "expert"
product_type = "unsmoothed"
#product_type = "wind-wave"

orbit = "1day_orbit"

SWOT_LR_L2_ftp = f"/data/swot_beta_products/l2_karin/l2_lr_ssh/{orbit}/{product_type}"
#SWOT_LR_L2_ftp = f"/data/swot_beta_products/l2_karin/l2_lr_ssh/21day_orbit/{product_type}"

In [10]:
db = NetcdfFilesFTPSwotLRL2(SWOT_LR_L2_ftp)

INFO:ocean_tools.interfaces.swath.io._utils:Successfully authenticated to ftp://ftp-access.aviso.altimetry.fr

In [11]:
db.last_date_available

numpy.datetime64('2023-07-09T22:58:58.000000')

In [12]:
# 474, 577
all_cycles = list(range(474, 578))

cycles = all_cycles[:50]
#passes = [1,2,3,4,5,6,7,8,9]
passes = [3,]

#files = db.list_files(cycle_numbers=[523, 524], pass_numbers=[1,2,3,4,5,6,7,8,9], sort=True)
files = db.list_files(cycle_numbers=cycles, pass_numbers=passes, sort=True)
files = files["filename"].values.tolist()
#pprint(files)
len(files)

45

In [ ]:
# leverage common directories
ds = db.query(cycle_numbers=cycles, pass_numbers=passes)
ds

INFO:ocean_tools.interfaces.swath.io._netcdf:Files to read: 45

In [ ]:
# minimal example
product_type = "unsmoothed"
orbit = "1day_orbit"
SWOT_LR_L2_ftp = f"/data/swot_beta_products/l2_karin/l2_lr_ssh/{orbit}/{product_type}"

db = NetcdfFilesFTPSwotLRL2(SWOT_LR_L2_ftp)

all_cycles = list(range(474, 578))
cycles = all_cycles[:5]
passes = [3,]

files = db.list_files(cycle_numbers=cycles, pass_numbers=passes, sort=True)
# leverage common directories
ds = db.query(cycle_numbers=cycles, pass_numbers=passes)
ds

In [ ]:
### local copy

local_dir = f"/work/HELPDESK_SWOTLR/swot_diego/{orbit}/{product_type}"
print(local_dir)

for file in tqdm(files):
    if not os.path.isfile(os.path.join(local_dir, file.split("/")[-1])):
        #try:
        db.retrieve_files([file], local_dir)
        #except:
        #    print("error file probably not found")

---

## 21day phase find passes

https://mybinder.org/v2/gh/fbriol/search_swot/HEAD?urlpath=voila%2Frender%2Fmain.ipynb

In [ ]:
import os, sys
lib_path = "/work/HELPDESK_SWOTLR/swot_diego/libs"
sys.path.append(os.path.join(lib_path, 'search_swot-master'))

In [ ]:
from package import MapSelection
MapSelection().display()

In [ ]:
## gibraltar

In [11]:
import pandas as pd

In [12]:
work_dir = "/work/HELPDESK_SWOTLR/swot_diego"
passes = os.path.join(work_dir, "gibraltar.csv")

In [19]:
df = pd.read_csv(passes, delimiter="\t", parse_dates=True)
df

,Unnamed: 0,cycle_number,pass_number,first_measurement,last_measurement
0,0,1,391,2023-08-04 04:33:59,2023-08-04 04:34:08
1,1,1,404,2023-08-04 15:42:44,2023-08-04 15:43:29
2,2,1,419,2023-08-05 04:34:29,2023-08-05 04:35:14
3,3,1,432,2023-08-05 15:43:15,2023-08-05 15:43:59
4,4,1,447,2023-08-06 04:35:00,2023-08-06 04:35:44
5,5,1,460,2023-08-06 15:43:46,2023-08-06 15:44:30
6,6,2,98,2023-08-14 14:05:35,2023-08-14 14:05:52
7,7,2,113,2023-08-15 02:56:53,2023-08-15 02:57:37
8,8,2,126,2023-08-15 14:05:38,2023-08-15 14:06:23
9,9,2,141,2023-08-16 02:57:24,2023-08-16 02:58:08
10,10,2,154,2023-08-16 14:06:09,2023-08-16 14:06:53
11,11,2,169,2023-08-17 02:57:54,2023-08-17 02:58:38
12,12,2,391,2023-08-25 01:19:06,2023-08-25 01:19:15
13,13,2,404,2023-08-25 12:27:52,2023-08-25 12:28:36
14,14,2,419,2023-08-26 01:19:37,2023-08-26 01:20:21
15,15,2,432,2023-08-26 12:28:22,2023-08-26 12:29:06
16,16,2,447,2023-08-27 01:20:07,2023-08-27 01:20:52
17,17,2,460,2023-08-27 12:28:53,2023-08-27 12:29:37
18,18,3,98,2023-09-04 10:50:40,2023-09-04 10:50:57
19,19,3,113,2023-09-04 23:41:58,2023-09-04 23:42:42
20,20,3,126,2023-09-05 10:50:43,2023-09-05 10:51:28
21,21,3,141,2023-09-05 23:42:29,2023-09-05 23:43:13
22,22,3,154,2023-09-06 10:51:14,2023-09-06 10:51:58
23,23,3,169,2023-09-06 23:42:59,2023-09-06 23:43:44
24,24,3,391,2023-09-14 22:04:11,2023-09-14 22:04:21
25,25,3,404,2023-09-15 09:12:57,2023-09-15 09:13:41
26,26,3,419,2023-09-15 22:04:42,2023-09-15 22:05:26
27,27,3,432,2023-09-16 09:13:27,2023-09-16 09:14:11
28,28,3,447,2023-09-16 22:05:13,2023-09-16 22:05:57
29,29,3,460,2023-09-17 09:13:58,2023-09-17 09:14:42
30,30,4,98,2023-09-25 07:35:45,2023-09-25 07:36:02
31,31,4,113,2023-09-25 20:27:03,2023-09-25 20:27:47
32,32,4,126,2023-09-26 07:35:49,2023-09-26 07:36:33
33,33,4,141,2023-09-26 20:27:34,2023-09-26 20:28:18
34,34,4,154,2023-09-27 07:36:19,2023-09-27 07:37:04
35,35,4,169,2023-09-27 20:28:04,2023-09-27 20:28:49
36,36,4,391,2023-10-05 18:49:16,2023-10-05 18:49:26
37,37,4,404,2023-10-06 05:58:02,2023-10-06 05:58:46
38,38,4,419,2023-10-06 18:49:47,2023-10-06 18:50:31
39,39,4,432,2023-10-07 05:58:32,2023-10-07 05:59:17
40,40,4,447,2023-10-07 18:50:18,2023-10-07 18:51:02
41,41,4,460,2023-10-08 05:59:03,2023-10-08 05:59:47
42,42,5,98,2023-10-16 04:20:48,2023-10-16 04:21:05
43,43,5,113,2023-10-16 17:12:05,2023-10-16 17:12:50
44,44,5,126,2023-10-17 04:20:51,2023-10-17 04:21:35
45,45,5,141,2023-10-17 17:12:36,2023-10-17 17:13:20
46,46,5,154,2023-10-18 04:21:22,2023-10-18 04:22:06
47,47,5,169,2023-10-18 17:13:07,2023-10-18 17:13:51

In [ ]:

def load_l2(product_type, passes, orbit="1day_orbit", cycles=None, side=None, **kwargs):
    from ocean_tools.interfaces.swath.io import NetcdfFilesFTPSwotLRL2
    SWOT_LR_L2_ftp = f"/data/swot_beta_products/l2_karin/l2_lr_ssh/{orbit}/{product_type}"
    db = NetcdfFilesFTPSwotLRL2(SWOT_LR_L2_ftp)
    #db.last_date_available
    if cycles is None and orbit=="1day_orbit":
        # select all cycles
        cycles = list(range(474, 578))
    if isinstance(passes, int):
        passes = [passes]
    _kwargs = dict(cycle_numbers=cycles, pass_numbers=passes) # cannot stack unsmoothed data
    _kwargs.update(**kwargs)
    if product_type=="Unsmoothed":
        assert side is not None, "specify side"
        _kwargs["group"] = side
    return db.query(**_kwargs)

load_l2("unsmoothed", [3], side="left")

---

## ERA

[ERA5 single levels doc](https://cds.climate.copernicus.eu/cdsapp#!/dataset/reanalysis-era5-single-levels?tab=overview)

In [1]:
import os
import cdsapi
import pandas as pd

assert "http_proxy" in os.environ
assert "https_proxy" in os.environ

overwrite=False

#OUTPUT_DIR = f'/work/scratch/data/{os.environ["USER"]}/tmp_data'
OUTPUT_DIR = f"/work/HELPDESK_SWOTLR/swot_diego/era5"

cds_client = cdsapi.Client()

dates = pd.date_range("2023/03/01", "2023/07/01", freq="1D")

In [7]:
day = dates[-1]
day, day.strftime("%Y%m%d")

(Timestamp('2023-07-01 00:00:00'), '20230701')

In [2]:

day = dates[0]
for day in dates:

    output_file = os.path.join(OUTPUT_DIR,f'reanalysis-era5-single-levels_{day.strftime("%Y%M%d")}.nc')

    if not os.path.isfile(output_file) or overwrite:
        cds_client.retrieve(
            'reanalysis-era5-single-levels',
            {
                'product_type': 'reanalysis',
                'format': 'netcdf',
                'variable': [
                    '10m_u_component_of_wind', '10m_v_component_of_wind', 'instantaneous_eastward_turbulent_surface_stress',
                    'instantaneous_northward_turbulent_surface_stress', 'significant_height_of_combined_wind_waves_and_swell', 'significant_height_of_wind_waves',
                    'surface_pressure',
                ],
                'year': day.year,
                'month': day.month,
                'day': day.day,
                'time': ['%02d:00'%(hour) for hour in range(24)],
            },
            output_file)